apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: 'ghcr.io/lsst-sitcom/protorubinportal'
    newTag: 0.0.0

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
